# SPDX-FileCopyrightText: Jason Xue <IcekingJason@outlook.com>
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["*.jpg", "*.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Jason Xue <IcekingJason@outlook.com>"
SPDX-License-Identifier = "CC0-1.0"
